version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
      - NODE_ENV=development
      - DOCKER_CONTAINER=true
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - weaviate
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smg_dialog
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smg_dialog
      - WEAVIATE_URL=http://weaviate:8080
      - VECTOR_TRANSFORMER_URL=http://t2v-transformer:8080
      - APP_ENV=development
      - FRONTEND_URL=http://frontend:3000
      - ADMIN_API_KEY=admin-secret-key-12345
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smg_dialog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  weaviate:
    image: semitechnologies/weaviate:1.24.1
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
      - TRANSFORMERS_INFERENCE_API=http://t2v-transformer:8080
    networks:
      - app-network

  t2v-transformer:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      - ENABLE_CUDA=0
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge