services:
  - type: web
    name: dialog-engine-frontend
    env: node
    region: frankfurt
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          name: dialog-engine-backend
          type: web
          property: url
    autoDeploy: true

  - type: web
    name: dialog-engine-backend
    env: python
    region: frankfurt
    plan: standard
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: POSTGRES_DB
        fromDatabase:
          name: dialog-engine-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: dialog-engine-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: dialog-engine-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: dialog-engine-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: dialog-engine-db
          property: port
    autoDeploy: true

databases:
  - name: dialog-engine-db
    region: frankfurt
    plan: free 